env:
  global:
    - secure: Id4Ztg0rzqPo7Qx8F3L2Y7TZyzqKcqs1/qL/nlVFv1QK4ISpEKprkIcEnxL97NJdIJCBqaqESkqzmMOII+l6a6zfLjHlze/aY3myhRY2DjcWwI5EC8IOq6zuGxkB7sclIX2DZvQOag4gW23d7grpI43tHeJLj4S9yHajxBcY41Q=
    - LD_LIBRARY_PATH=/usr/local/lib
install:
  - curl https://static.rust-lang.org/rustup.sh | sudo sh -
  - wget http://www.fmod.org/download/fmodex/api/Linux/fmodapi44439linux.tar.gz
  - tar xvf fmodapi44439linux.tar.gz
  - sudo cp -r fmodapi44439linux/api/lib/* /usr/local/lib/.
script:
  - rustc --version
  - cargo build
  - rustdoc -o doc src/rfmod.rs
after_script:
  - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh