env:
  global:
    - LD_LIBRARY_PATH=/usr/local/lib
before_install:
  - yes | sudo add-apt-repository ppa:cmrx64/cargo
  - sudo apt-get update
install:
  - sudo apt-get install cargo
  - curl http://www.rust-lang.org/rustup.sh | sudo sh -
  - wget http://www.fmod.org/download/fmodex/api/Linux/fmodapi44439linux.tar.gz
  - tar xvf fmodapi44439linux.tar.gz
  - sudo cp -r fmodapi44439linux/api/lib/* /usr/local/lib/.
script:
  - rustc --version
  - cargo build
  - rustdoc -o doc src/rfmod.rs
after_script:
  - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh