[package]

name = "fmod"
version = "0.9.5"
authors = ["Guillaume Gomez <guillaume1.gomez@gmail.com>"]

description = "A rust binding for the FMOD library"
repository = "https://github.com/GuillaumeGomez/rust-fmod"
documentation = "http://rust-ci.org/GuillaumeGomez/rust-fmod/doc/rfmod/"
readme = "README.md"
keyworks = ["library", "sound", "3D", "fmod", "fmodex", "FMOD", "FMODEX"]
license = "FMOD non-commercial use"

[lib]

name = "rfmod"
crate-type = ["dylib", "rlib"]

[[bin]]

name = "recording"
path = "examples/recording/main.rs"

[[bin]]

name = "simple_music_player"
path = "examples/simple_music_player/main.rs"

[[bin]]

name = "dsp_custom"
path = "examples/dsp_custom/main.rs"

[[bin]]

name = "user_created_sound"
path = "examples/user_created_sound/main.rs"

[[bin]]

name = "3d"
path = "examples/3d/main.rs"

[[bin]]

name = "effects"
path = "examples/effects/main.rs"

[[bin]]

name = "file_callbacks"
path = "examples/file_callbacks/main.rs"