[package]

name = "rust-fmod"
version = "0.8.0"
authors = ["Guillaume Gomez <guillaume1.gomez@gmail.com>"]

[[lib]]

name = "rfmod"
crate-type = ["dylib", "rlib"]

[[bin]]

name = "recording"
path = "examples/recording/main.rs"

[[bin]]

name = "simple_music_player"
path = "examples/simple_music_player/main.rs"

[[bin]]

name = "dsp_custom"
path = "examples/dsp_custom/main.rs"

[[bin]]

name = "user_created_sound"
path = "examples/user_created_sound/main.rs"

[[bin]]

name = "3d"
path = "examples/3d/main.rs"

[[bin]]

name = "effects"
path = "examples/effects/main.rs"

[[bin]]

name = "file_callbacks"
path = "examples/file_callbacks/main.rs"