[package]
name = "fmod"
version = "0.9.11"
authors = ["Guillaume Gomez <guillaume1.gomez@gmail.com>"]

description = "A rust binding for the FMOD library"
repository = "https://github.com/GuillaumeGomez/rust-fmod"
documentation = "http://rust-ci.org/GuillaumeGomez/rust-fmod/doc/rfmod/"
readme = "README.md"
keywords = ["library", "sound", "3D", "fmod", "fmodex"]
license-file = "LICENSE.TXT"

[dependencies]
c_str = "^1.0.0"
c_vec = "^1.0.0"

[lib]
name = "rfmod"
crate-type = ["dylib", "rlib"]